**Exercícios inspirados no módulo de Numpy, do Bootcamp em Data Science e Machine Learning da Udemy**

In [2]:
import numpy as np

In [17]:
#retornar números aleatórios entre 0 e 1
np.random.rand(2)

array([0.73623062, 0.02645975])

In [7]:
#array de 0's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#array de 1's
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
#aplicando operações matematicas em np.arrays
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [9]:
#array de inteiros, parametros da função arange(inicio, fim, intervalo)
np.arange(10, 100, 4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [10]:
#transformando array em matrix
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#matriz identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#mais operações com arrays
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#somando os valores
c.sum()

36

In [24]:
#somando as linhas
c.sum(axis=1)

array([ 3, 12, 21])

In [23]:
#somando colunas
c.sum(axis=0)

array([ 9, 12, 15])

In [21]:
#calculando desvio padrão 
c.std()

2.581988897471611